### ISSUE TITLE
Project name is too similar to existing project name

### ISSUE THREAD

**Issue by workhorsy** [dariusk/TheEthicalAdBlocker#3]
Hello. I've been working on my own ad blocker called "Ethical Ad Block" since June 28th. Your project "The Ethical Ad Blocker" has a very similar name to mine. Can you change the name to be less similar?

https://github.com/workhorsy/ethical_ad_block

**Comment by dariusk** [comment]
I'm sorry that this happened. I googled for "ethical ad blocker" and your project didn't come up. I'm guessing because it's only a github repo and the readme doesn't even contain the string "ethical ad blocker" (instead it uses underscores).

Unfortunately I think I did my due dilligence and having a stub of a project that hasn't been released yet (and doesn't even use a discoverable project name to begin with) doesn't really lay any kind of moral right to a name. From my end, I'm fine with you releasing it as "Ethical Ad Block" -- I would even link to it from the home page of my own project.
